# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 109ea7ef3e0dccd2f115014a94e4303222fee8e1114f0a644489aff9f0f22bf787ab36ba757e041f8fdcd18fb1980b9a62586a0292d70fa46b363e8455b34f41

test:
  secret_key_base: e5c0d8ce9bcfdfca7bff6a8e9af6a7760913bdce10b42fc5367c0b29f3c1b9eddfa0ce3073ff018810ec33f407d3ad5a7384ac725909cfbdc6bfa90f8617aeb1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
